### ISSUE TITLE
Add button to Issue Detail Page

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-ChromeExt#1]
### Description
In this first of several challenges, we're going to build a Chrome extension that launches challenges on the Topcoder platform with the click of a button from a Github issue. 

### Requirement: 
The Chrome extension should: 

- add a button to any Issue Detail page inside github
- when clicking the button, check for a Github oAuth token in extension's local storage
  + if no token, then enter the "oAuth Dance" for Github, retrieve a token and store it in local storage. (See: [Create an app](https://github.com/settings/applications/new) and [oAuth](https://developer.github.com/v3/oauth/) )
  + if token is present then POST the issue details to the [TC Challenge Mock endpoint](https://glib-mock.herokuapp.com)
- add a comment to the issue ticket stating the success (or failure) of the challenge endpoint, including the URL of the challenge created 
- fork this repo and target [this branch](https://github.com/cloudspokes/GLIB-ChromeExt/tree/30052923-challenge01) when making pull requests

### SUBMISSION:
- Upload documentation for how to run your submission
- Upload all your source code as a zip
- Provide a video overview of your submission. Please describe what you did in the video.
- Winner will be required to submit a pull request against the branch specified!

![image](https://cloud.githubusercontent.com/assets/1504607/12836170/5328a674-cb84-11e5-95b8-214248f47368.png)

**Comment by dmessing** [comment]
Challenge created successfully
Challenge Url: http://topcoder.com

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T04:54:09.030Z

**Comment by cwdcwd** [comment]
closing on #4
