### ISSUE TITLE
Add topcoder logo to button

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-ChromeExt#12]
Add a small topcoder logo to button

**Comment by cwdcwd** [comment]
@kbowerma @dmessing @wdprice do you guys have a real tiny TC icon we can use? I want to spiffy up that button

**Comment by wdprice** [comment]
No but I have a high res version and photoshop...

**Comment by dmessing** [comment]
Ask Rash

**Comment by cwdcwd** [comment]
:-1:

**Comment by wdprice** [comment]
![tiny_tc](https://cloud.githubusercontent.com/assets/6014049/13297679/7c92b11c-db01-11e5-9160-f7ee882b28f7.png)

@cwdcwd Try this, too pixely?

**Comment by wdprice** [comment]
Bah, still too big

**Comment by wdprice** [comment]
![tiny_tc](https://cloud.githubusercontent.com/assets/6014049/13297742/d0f89c08-db01-11e5-8d04-602d35e745b5.png)

Shrunk by 50%

**Comment by wdprice** [comment]
@cwdcwd YOU LIKEY?

**Comment by cwdcwd** [comment]
:+1:  thanks @wdprice

**Comment by cwdcwd** [comment]
@wdprice @dmessing @kbowerma check it out yo! 

<img width="1150" alt="screen shot 2016-02-25 at 9 35 37 pm" src="https://cloud.githubusercontent.com/assets/1504607/13341556/c4f6ba0a-dc07-11e5-8608-ee3378352dc2.png">

**Comment by cwdcwd** [comment]
closing on 09178c7c4af966479de56cd2c57674d23728298b

**Comment by cwdcwd** [comment]
![tc-button](https://cloud.githubusercontent.com/assets/17499676/13359374/89d0e73a-dc79-11e5-81ff-d55fcd483c7a.png)
