### ISSUE TITLE
[$300,$150] Create Options Screen

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-ChromeExt#2]
### Description:
This is an expansion on the [GLIB-GITHUB-TOPCODER CHROME EXTENSION Challenge](https://www.topcoder.com/challenge-details/30052923/?type=develop&noncache=true). 

### Requirements:
Create a settings/options screen for the extension to:
- manage github authorization. Revoke/delete token.
- manage topcoder authorization. Revoke/delete token.
- map github repo to topcoder project. Take current repo path and map to an Id number. Maintain a list of repos and Ids in an array that's editable.
- screen can be accessed from the Chrome Extensions settings list 
 
![image](https://cloud.githubusercontent.com/assets/1504607/13451441/05613b16-e00d-11e5-9a52-270bab614981.png)

### Submissions:
Upload documentation for how to run your submission
Upload all your source code as a zip
Winner will be required to submit a pull request against [the branch specified](https://github.com/cloudspokes/GLIB-ChromeExt/tree/settings) !

**Comment by dmessing** [comment]
Challenge created successfully
Challenge Url: http://topcoder.com

**Comment by 852719** [comment]
Challenge created successfully
Challenge Url: http://topcoder.com

**Comment by cwdcwd** [comment]
closing on #15
