### ISSUE TITLE
Create Comment on issue ticket 

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-ChromeExt#3]
after successful launch of a challenge, create comment on ticket with challenge details and URL to view challenge

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:25:48.854Z

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:25:54.534Z

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:25:55.562Z

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:26:41.588Z

**Comment by Eronana** [comment]
TC Challenge status: failure
Challenge URL: undefined
Created Date: undefined

**Comment by Eronana** [comment]
TC Challenge status: failure
Challenge URL: undefined
Created Date: undefined

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:38:52.377Z

**Comment by Eronana** [comment]
TC Challenge status: success
Challenge URL: http://topcoder.com
Created Date: 2016-02-12T06:53:17.095Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T08:41:54.316Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T10:40:45.897Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T10:43:40.538Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T10:43:56.830Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T12:21:08.959Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T12:21:20.073Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T12:21:58.224Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T13:21:28.736Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T13:24:17.766Z

**Comment by GEETAMAMUNI** [comment]
TC Launch Status: Success
TC Challenge URL: http://topcoder.com
Created Date: 2016-02-12T13:40:21.937Z

**Comment by cwdcwd** [comment]
closing on !4
