### ISSUE TITLE
Crashing Chrome

### ISSUE THREAD

**Issue by kbowerma** [cloudspokes/GLIB-ChromeExt#31]
### Description:
Sometimes my github (not necessarily  issues page ) seems to lockup and nothing on the browser tab works however the other tabs seem fine.    I have a lot of windows and several tabs open. 
<img width="505" alt="screen shot 2016-04-06 at 2 57 10 pm" src="https://cloud.githubusercontent.com/assets/1180747/14331575/920e3824-fc0b-11e5-9809-6039acfaeb14.png">

### Requirements:
Please investigate and let us know if you are experiencing it to.  I also have zenhub extension running

***update several minutes later***
I think this is related to zenhub because although it was not crashing it was very slow to respond.   I just disabled zenhub and now it  every char a type is realtime.

**Comment by cwdcwd** [comment]
ah ha! what does Zenhub inject? perhaps there's a conflict between the two?

**Comment by kbowerma** [comment]
it is not zenhub, I removed it.    My work around is to have github open in an incognito tab which does not have blib enabled.   But we will have to figure this out since it will happen with others too.

**Comment by cwdcwd** [comment]
Can you pop open a console when you see this happen and see if there's any errors or something loggin out?

**Comment by kbowerma** [comment]
I will keep looking but this is what I have so far:

```javascript
content_script.js:57 Uncaught TypeError: Cannot read property 'appendChild' of nullinjectStyles @ content_script.js:57(anonymous function) @ content_script.js:67
```

And there is line 57:   ```  document.body.appendChild(node);```

```javascript
/**
 * Try to inject topcoder buttons on issues list and issue detail page.
 * This is infinite interval, because page content can be updated dynamically
 * (when new comment is added or because of html5 navigation).
 */
function injectStyles() {
    var node = document.createElement('link');
    node.rel = 'stylesheet';
    node.href = chrome.extension.getURL('styles/style.css');
    document.body.appendChild(node);
```

I repeated the same steps in my incognito window and don't see the error

**Comment by cwdcwd** [comment]
interesting. so that's where the style sheet for the button gets injected into the page. 

The incognito thing is interesting. Can you dump me your list of extensions and see which ones are enabled/disabled in incognito mode?

**Comment by kbowerma** [comment]
sure will.    I am sure it this extension but it can be very intermittent   What happens is git is open for a long time.    It just gets slower and slower until every char typing takes about a second to display.   Could be network related?  other times it works ok light right now.

**Comment by kbowerma** [comment]
[topcoder] 0.2
Quick and handy access to the latest [topcoder] challenges.
Permissions Details
ID: ngmdhhjaomeigcmmnjiecenogfkcgnhe

Enable
  
AngularJS Batarang 0.10.7
Extends the Developer Tools, adding tools for debugging and profiling AngularJS applications.
Permissions Details
ID: ighdmehidhipcmcojjgiloacoafjmpfk
Inspect views: background page

Allow in incognito
  
Allow access to file URLs
Warning: Google Chrome cannot prevent extensions from recording your browsing history. To disable this extension in incognito mode, unselect this option.

Enabled
  
Bitly | Unleash the power of the link 2.1.1
Save, share, and brand your links
Permissions Options Details
ID: iabeihobmhlgpkcgjiloemdbofjbdcic
Inspect views: html/background.html

Allow in incognito
 
Enabled
  
BuiltWith Technology Profiler 2.4
Find out what the website you are visiting is built with using this extension.
Permissions Details
ID: dapjbgnjinbpoindlpdmhochffioedbn

Allow in incognito
 
Enabled
  
CCTV View 1.1.0.6
Watch up to 20 webcams or CCTV cams within your browser.
Permissions Developer website
ID: oajmcmcpiboagipoflploplebgicaadj

Enable
  
Cisco WebEx Extension 1.0.1
Join WebEx meetings using Google Chrome ™
Permissions Details
ID: jlhmfgmfgeifomenelglieieghnjghma
Inspect views: background page

Allow in incognito
 
Enabled
  
Codebender App 1.0.0.8
Arduino Programming & Serial Monitor App by codebender
Permissions Details
ID: magknjdfniglanojbpadmpjlglepnlko
Inspect views: background.html (Inactive)

Allow in incognito
 
Enabled
  
Codebender.cc Extension 1.6.1.0
Codebender.cc Arduino Communication
Permissions Details
ID: fkjidelplakiboijmadcpcbpboihkmee

Allow in incognito
 
Enabled
  
Discover DevTools Companion 0.2.13
Permissions Details
ID: angkfkebojeancgemegoedelbnjgcgme

Enable
  
Evernote Web Clipper 6.7.1
Use the Evernote extension to save things you see on the web into your Evernote account.
Permissions Options Details
ID: pioclpoplcdbaefihamjohnefbikjilc
Inspect views: background.html

Allow in incognito
  
Allow access to file URLs
 
Enabled
  
Extended S3 Browser 1.0.7
An extension to browse S3 files on your chrome browser brought to you by Lereve Labs (www.lerevelabs.com).
Permissions Details
ID: ddmmmnnbkhpkgnkafpflhaoohifpdkmg
Inspect views: background page

Allow in incognito
 
Enabled
  
feedly 34
All your favorite sites in one place.
Permissions Details
ID: hipbfijinpcgfogaopmgehiegacbhmob

Enable
  
Ghost Editor - RAW TEXT Button 1.1
Adds RAW TEXT button to your ghost editor. Switches editor to the simple mode where the browser spell checking is working.
Permissions Details
ID: flcgagocnilfdaigipejmegagelhpafd
Inspect views: background page

Allow in incognito
 
Enabled
  
GLIB-ChromeExt 1.0
GLIB-ChromeExt
Permissions Options Details
ID: fbdelahfocadoeclphgckagbmjpcnpkd

Allow in incognito
 
Enabled
  
Google Docs 0.9
Create and edit documents
Permissions Details
ID: aohghmighlieiainnegkcijnfilokake

Allow in incognito
 
Enabled
  
Google Docs Offline 1.4
Get things done offline with the Google Docs family of products.
Permissions Details
ID: ghbmnnjooekpmoecnnnilnnbdlolhkhi
Inspect views: background page (Inactive)

Allow in incognito
 
Enabled
  
Google Hangouts 2015.1204.418.1
Hangouts brings conversations to life with photos, emoji, and even group video calls for free.
Permissions Options Details
ID: nckgahadagoaajjgafhacjanaoiihapd
Inspect views: background page (iframe) background pagebackground page (iframe)

Allow in incognito
 
Enabled
  
Google Sheets 1.1
Create and edit spreadsheets
Permissions Details
ID: felcaaldnbdncclmgdcncolpebgiejap

Enable
  
Google Slides 0.9
Create and edit presentations
Permissions Details
ID: aapocclcgogkmnckokdopfmhonfmgoek

Enable
  
GoToMeeting for Google Calendar 3.10
Easily schedule GoToMeeting sessions from your Google Calendar.
Permissions Options Developer website
ID: gaonpiemcjiihedemhopdoefaohcjoch
Inspect views: background page (Inactive)

Allow in incognito
 
Enabled
  
JSONView 0.0.32.2
Validate and view JSON documents
Permissions Options Details
ID: chklaanhfefbnpoihckbnefhakgolnmc
Inspect views: background page

Allow in incognito
  
Allow access to file URLs
Warning: Google Chrome cannot prevent extensions from recording your browsing history. To disable this extension in incognito mode, unselect this option.

Enabled
  
KeyRocket for Gmail™ 0.7.3.2
The best way to learn keyboard shortcuts while you work in Gmail™ by http://www.keyrocket.com.
Permissions Details
ID: dmocchgkijnbjdjkmlglaemjhhdiobbp

Enable
  
LastPass: Free Password Manager 4.1.5
LastPass, an award-winning password manager, saves your passwords and gives you secure access from every computer and mobile device.
Permissions Options Details
ID: hdokiejnpimakedhajhdlcegeplioahd
Inspect views: background.html

Allow in incognito
  
Allow access to file URLs
Warning: Google Chrome cannot prevent extensions from recording your browsing history. To disable this extension in incognito mode, unselect this option.

Enabled
  
Mailvelope 1.3.6
Enhance your webmail provider with end-to-end encryption. Secure email communication based on the OpenPGP standard.
Permissions Developer website
ID: kajibbejlbohfaggdiogboambcijhkke

Enable
  
Markdown Here 2.12.0
Write your email in Markdown, then make it pretty.
Permissions Options Developer website
ID: elifhakcjgalahccnjkneoccemfahfoa
Inspect views: chrome/background.html

Allow in incognito
 
Enabled
  
Okta Secure Web Authentication Plug-in 5.5.0
Okta Secure Web Authentication Plug-in
Permissions Details
ID: glnpjglilkicbckjpbgcfkogebgllemb
Inspect views: background.html

Allow in incognito
 
Enabled
  
PageSpeed Insights (by Google) 2.0.4.3
PageSpeed Insights analyzes the performance of your web pages and provides suggestions to make them faster.
Permissions Developer website
ID: gplegfbjlmmehdoakndmohflojccocli

Enable
  
Pocket 0.810
Over 10 million people use Pocket to easily save articles, videos and more for later.
Permissions Details
ID: mjcnijlhddpbdemagnpefmlkjdagkogk
Inspect views: background page (Inactive)

Allow in incognito
  
Allow access to file URLs
 
Enabled
  
Postman 4.1.3
Permissions Details
ID: fhbjgbiflinjbdggehcddcbncdddomop
Inspect views: background page (Inactive)

Allow in incognito
 
Enabled
  
Postman - REST Client 0.8.4.17
Permissions Details
ID: fdmmgilgnpjigdojojpjoooidkmcomcm

Enable
  
Pushbullet 325
Bringing together your devices, friends, and the things you care about.
Permissions Options Developer website
ID: chlffgpmiacpedhhbkiomidkjlcfhogd
Inspect views: background page

Allow in incognito
 
Enabled
  
Read Later Fast 1.6.18
Save pages to read later -- online or offline, and fast! Avoid too many tabs and make your browsing a blast!
Permissions Details
ID: decdfngdidijkdjgbknlnepdljfaepji

Enable
This extension violates the Chrome Web Store policy.
  
REST Console 4.0.2
REST Console is an HTTP Request Visualizer and Constructor tool, helps developers build, debug and test RESTful APIs.
Permissions Details
ID: cokgbflfommojglbmbpenpphppikmonn

Enable
  
Save to Pocket 1.9.38
Pocket Extension for Chrome - The best way to save articles, videos and more
Permissions Options Details
ID: niloccemoadcdkdjlinkgdfekeahmflj
Inspect views: html/background.html

Allow in incognito
 
Enabled
  
Speed Tracer (by Google) 0.27
Get insight into the performance of your web applications.
Permissions Details
ID: ognampngfcbddbfemdapefohjiobgbdl

Enable
This extension contains a serious security vulnerability.
  
TechSmith Snagit 2.0.3.354
Screen capture, screen recording, image editing, and sharing. Collaborate and show what you know.
Permissions Details
ID: fcnghgbgmemnlbckdipnmelbanpgneik

Enable
  
Tweet this page 2.27
Share currently viewed page on Twitter. Automatically shortens long URLs if needed.
Permissions Options Details
ID: ppilhaolhbpfembaoedfdbkegfedfgip
Inspect views: background page

Allow in incognito
 
Enabled
  
Viewstate indicator 1.1
Shows the amount of viewstate on the page
Permissions Details
ID: mhfgbepafobiainjedlonoanghiedllg

Enable
  
ZenHub for GitHub 2.16.27
ZenHub – Project Management Inside GitHub
Permissions Details
ID: ogcgkffhplmphkaahpmffcafajaocjbd

**Comment by cwdcwd** [comment]
thanks for that. 
So the ext's content script runs at "document start" (see [this](https://github.com/cloudspokes/GLIB-ChromeExt/blob/master/manifest.json#L32)). I wonder if, because of github's background polling for updates, it's firing constantly. When you inspect the page, is that injection putting tons of link tags in? 
that's all speculation as none of that explains the incognito working out.

**Comment by cwdcwd** [comment]
FWIW I recently disabled "Markdown Here" as it was grinding everything to a halt at random times

**Comment by kbowerma** [comment]
that might be it.    Like I said on the phone it seems like it may have fixed itself.    I will close this ticket and we can open if it comes back.
