### ISSUE TITLE
[$400, $200] Update GLIB Chrome Extension - Update Topcoder Auth

### ISSUE THREAD

**Issue by gbockus** [cloudspokes/GLIB-ChromeExt#36]
### Description:
The GLIB-Chrome-Ext challenges are a set of challenges where we will be building out a chrome extension that inserts a button onto various vendor (Github, Gitlab, Jira, etc) sites in order to launch a new Topcoder challenge(s).  This challenge will be removing the replacing the current topcoder token retrieval with an updated endpoint that uses and implicit grant. 

### Requirements:
- Remove the current Topcoder token retrieval code.
- Add functionality for retrieving a Topcoder token using the implicit grant Topcoder service. The client_id etc will be added to the forum.  Note that it uses a callback url so you will need to add a listener in the background script for handling the callback and storing the information related to the returned JWT token.
- Parse the returned JWT token and save the details into chrome storage.
- Update the extension to check the expiration date on the token prior to using it and refresh it if necessary. 

### Setup & Reference:
- Use dev mode when working on the extension locally.   This is configured in the options of the extension.
- See the README for details around running the extension locally. 
- For dev mode you are able to enter any value for the project id when prompted. 
- Fork this [repo](https://github.com/cloudspokes/GLIB-ChromeExt) and work off this [branch](https://github.com/cloudspokes/GLIB-ChromeExt/tree/updateTopcoderAuth).
- The calls to topcoder endpoints will fail with the new token.  This is expected.  We will update the extension to use new endpoints in future challenges. For this challenge you only need to demonstrate that you have stored the token and that it is refreshed when the expiration time is passed. 
- Feel free to add JWT processing module to the project. 

### Submissions:

- Upload documentation for how to run your submission
- A video of your working solution is required
- Upload all your source code as a zip for review
- Winner will be required to submit a pull request with their winning code.

**Comment by cwdcwd** [comment]
👍

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n      <style type=\"text/css\">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src=\"//s3.amazonaws.com/heroku_pages/error.html\">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>"
```

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050395/?type=develop&noncache=true
