### ISSUE TITLE
[?] GLIB Chrome Extension - Alter button injection

### ISSUE THREAD

**Issue by gbockus** [cloudspokes/GLIB-ChromeExt#37]
### Description:
The GLIB-Chrome-Ext challenges are a set of challenges where we will be building out a chrome extension that inserts a button onto various vendor (Github, Gitlab, Jira, etc) sites in order to launch a new Topcoder challenge(s).  This this challenged we will be altering the code that does the button injection as it is currently causing the page to freeze up on Github after a period of time.  We will be updating the extension to use chome events that are triggered on updates to the page that will check the url on updates and only inject the styles and button when the appropriate url is detected. 

### Requirements:
- Add tabs to the permission object in the manifest.
- In the background.js script add a `chrome.tabs.onUpdated` event handler that will check the current url to determine if the styles need to be injected and button added.  Note the event will fire multiple times for a single page navigation (such as clicking issues in github). Your code should verify that the styles and button have not already been injected for the current view.
- Use the chrome.tab.injectCss function add the required styles to the active tab.  
- Update the code to add the button to the page when necessary.  This can either be done using something like chome.tab.executeScript (note there will need to be a custom setup per vendor), or by firing an event to be handled in the contest_script.js that will use the current button injection code. 
- Depending on your implementation update or removed the code in the content_script that is no longer necessary.  Note that the purpose of this challenge is to remove the setInterval functions from the button injects so be sure that those are removed.
- Update the code that is executed on load, removing the button and style inject checks.
- It would be ideal if the `chome.tab.onUpdated listener was only added when a valid vendor is detected.  Explore this possibility and document in your submission if you were not able to accomplish this goal.
- Add  a common logging function that uses console.log, but will only log out when the extension in developer mode.  You added function should use this logging function to console.log out statements indicating execution in the extension. 
- Ensure that the gulpfile tasks and scripts in package.json all still pass after you updates.  You should add unit test for added functionality. 

### Setup & Reference:
- Use dev mode when working on the extension locally.   This is configured in the options of the extension.
- See the README for details around running the extension locally. 
- For dev mode you are able to enter any value for the project id when prompted. 
- Fork this [repo](https://github.com/cloudspokes/GLIB-ChromeExt) and work off this [branch](https://github.com/cloudspokes/GLIB-ChromeExt/tree/removeSetInterval).
- https://developer.chrome.com/extensions/tabs
- https://developer.chrome.com/extensions/event_pages

### Submissions:

- Upload documentation for how to run your submission
- A video of your working solution is required
- Upload all your source code as a zip for review
- Winner will be required to submit a pull request with their winning code.

**Comment by cwdcwd** [comment]
$200 max maybe?

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: undefined
Response body:
```
"empty response"
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: undefined
Response body:
```
"empty response"
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "message": "'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjA3NjUzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIwNzA1MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiZjYwYTM1YjUtMmVmYS00NWMyLTk2ZjMtNzdjMmY1ODAzOGZlIn0.oDlGsqXbQVg5tSOErZ68qGNfOu_fUIIY-wTBWXMpRU0' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjA3NjUzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIwNzA1MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiZjYwYTM1YjUtMmVmYS00NWMyLTk2ZjMtNzdjMmY1ODAzOGZlIn0.oDlGsqXbQVg5tSOErZ68qGNfOu_fUIIY-wTBWXMpRU0'.",
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "message": "'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjA3NjUzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIwNzA1MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiZjYwYTM1YjUtMmVmYS00NWMyLTk2ZjMtNzdjMmY1ODAzOGZlIn0.oDlGsqXbQVg5tSOErZ68qGNfOu_fUIIY-wTBWXMpRU0' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjA3NjUzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIwNzA1MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiZjYwYTM1YjUtMmVmYS00NWMyLTk2ZjMtNzdjMmY1ODAzOGZlIn0.oDlGsqXbQVg5tSOErZ68qGNfOu_fUIIY-wTBWXMpRU0'.",
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "message": "'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjI2NTgzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIyNTk4MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiOWUzOWJhODItMDBmOS00ODc3LTlhMzktNzhmZDk3OWI0OTZlIn0.-_UjY5fmJ61gYs44hc24OZKKZp6CGQZ_Zb0Qm46MZHA' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W10sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6ImxhenliYWVyIiwiZXhwIjoxNDY0MjI2NTgzLCJ1c2VySWQiOiIyMzIyNTU0NCIsImlhdCI6MTQ2NDIyNTk4MywiZW1haWwiOiJjd2RAdG9wY29kZXIuY29tIiwianRpIjoiOWUzOWJhODItMDBmOS00ODc3LTlhMzktNzhmZDk3OWI0OTZlIn0.-_UjY5fmJ61gYs44hc24OZKKZp6CGQZ_Zb0Qm46MZHA'.",
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:115:22)",
        "exports.handler (/var/task/index.js:378:13)"
    ],
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:115:22)",
        "exports.handler (/var/task/index.js:378:13)"
    ],
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30054390/?type=develop&noncache=true

**Comment by cwdcwd** [comment]
@gbockus closing out unless you think otherwise

**Comment by gbockus** [comment]
I think we're good 👍
