### ISSUE TITLE
Need guidance before Pull Request

### ISSUE THREAD

**Issue by thkang2** [cloudspokes/GLIB-ChromeExt#39]
Hi, as the Appeals Response phase has ended I understand that I'll be sending a pull request, I think some clarifications are needed before actually sending  them.

You can see the latest version at [https://github.com/thkang2/GLIB-ChromeExt/tree/updateTopcoderAuth](https://github.com/thkang2/GLIB-ChromeExt/tree/updateTopcoderAuth)

1. The challenge creation function - they're disabled. Before my change the button started a chain of promises, which did (simplified) `1)Authenticate - 2)Submit challenge to topcoder server - 3)post comments to github/jira/gitlab server`. Currently the button just `alert` you a json web token. No challenge posting. Should I leave this or change them?

2. Please download the extension and go to the options page. It has more fields that I added. I just made them so reviewers can see it but really don't think they are necessary as they should be internals and not be configurable.

3. Should I include the mock oauth server?

4. It seems chrome extension doesn't have any javascript `import/require` system, instead it relies on some kind of script injection by creating a background.html on the fly and insert js files via `<script src="..">` in the order of them in `manifest.json`. This breaks code linting as there will be undeclared globals. Any solution on this?

**Comment by gbockus** [comment]
1. Change it back to the original flow, but using your JWT token auth code. .
2. Also revert the options to the original state.
3.  Sure leave it in.  You might add a README to that directory with instructions on how to use it.
4. Update the linting options to specifically include exceptions for the globals required.

Thanks

**Comment by thkang2** [comment]
@gbockus Please check https://github.com/cloudspokes/GLIB-ChromeExt/pull/40

Thanks!

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
Failed to create challenge
Status code: 500
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Cannot read property &#x27;replace&#x27; of undefined</h1>\n<h2></h2>\n<pre>TypeError: Cannot read property &#x27;replace&#x27; of undefined\n    at module.exports (/app/node_modules/jwt-decode/lib/base64_url_decode.js:14:19)\n    at module.exports (/app/node_modules/jwt-decode/lib/index.js:10:21)\n    at fMassageV3Payload (/app/routes/index.js:70:17)\n    at /app/routes/index.js:280:23\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/app/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at /app/node_modules/express/lib/router/index.js:267:22\n    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)</pre>\n\n  </body>\n</html>\n"
```

**Comment by gbockus** [comment]
Failed to create challenge
Status code: 500
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Cannot read property &#x27;replace&#x27; of undefined</h1>\n<h2></h2>\n<pre>TypeError: Cannot read property &#x27;replace&#x27; of undefined\n    at module.exports (/app/node_modules/jwt-decode/lib/base64_url_decode.js:14:19)\n    at module.exports (/app/node_modules/jwt-decode/lib/index.js:10:21)\n    at fMassageV3Payload (/app/routes/index.js:70:17)\n    at /app/routes/index.js:280:23\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/app/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at /app/node_modules/express/lib/router/index.js:267:22\n    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)</pre>\n\n  </body>\n</html>\n"
```

**Comment by gbockus** [comment]
Failed to create challenge
Status code: 500
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Cannot read property &#x27;replace&#x27; of undefined</h1>\n<h2></h2>\n<pre>TypeError: Cannot read property &#x27;replace&#x27; of undefined\n    at module.exports (/app/node_modules/jwt-decode/lib/base64_url_decode.js:14:19)\n    at module.exports (/app/node_modules/jwt-decode/lib/index.js:10:21)\n    at fMassageV3Payload (/app/routes/index.js:70:17)\n    at /app/routes/index.js:280:23\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/app/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at /app/node_modules/express/lib/router/index.js:267:22\n    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)</pre>\n\n  </body>\n</html>\n"
```
