### ISSUE TITLE
[$150] Prompt user for credentials

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-ChromeExt#7]
### Description:
This is an expansion on the [GLIB-GITHUB-TOPCODER CHROME EXTENSION Challenge](https://www.topcoder.com/challenge-details/30052923/?type=develop&noncache=true). 

Instead of hardcoding the TC [username](https://github.com/cloudspokes/GLIB-ChromeExt/blob/develop/config.js#L15) and [password](https://github.com/cloudspokes/GLIB-ChromeExt/blob/develop/config.js#L16), prompt the user for their credentials before fetching the auth token

### Requirements:
- fork this repo and work off [this branch](https://github.com/cloudspokes/GLIB-ChromeExt/tree/30053039-prompt)
- replace [username](https://github.com/cloudspokes/GLIB-ChromeExt/blob/develop/config.js#L15) and [password](https://github.com/cloudspokes/GLIB-ChromeExt/blob/develop/config.js#L16) with a prompt for the user for the credentials

### Submissions:
Upload documentation for how to run your submission
Upload all your source code as a zip
Winner will be required to submit a pull request against [the branch specified](https://github.com/cloudspokes/GLIB-ChromeExt/tree/30053039-prompt) !

**Comment by 852719** [comment]
Challenge created successfully
Challenge Url: http://topcoder.com

**Comment by 852719** [comment]
Challenge created successfully
Challenge Url: http://topcoder.com

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30049598/?type=develop&noncache=true

**Comment by cwdcwd** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30049613/?type=develop&noncache=true

**Comment by cwdcwd** [comment]
closing on fc4428ab95910af2358fcfce3088a9f29c0fc4d9
